# More info at https://docs.python.org/3/extending/building.html#building
# For windows look at https://docs.python.org/3/extending/windows.html#building-on-windows

default:
	python3 setup.py build
	python3 setup.py install
source:
	python3 setup.py sdist
.PHONY: default source